version: "3.7"

services:
    dotnetarchitecture_web:
        build:
            context: .
            dockerfile: dockerfile
            args:
                ANGULAR_ENVIRONMENT: container
                ASPNETCORE_ENVIRONMENT: Container
        image: dotnetarchitecture_web
        container_name: dotnetarchitecture_web
        depends_on:
            - dotnetarchitecture_mssqlserver
        networks:
            - network
        ports:
            - 8095:80
    dotnetarchitecture_mssqlserver:
        image: microsoft/mssql-server-linux
        container_name: dotnetarchitecture_mssqlserver
        environment:
            ACCEPT_EULA: Y
            SA_PASSWORD: P4ss-W0rd!
        networks:
            - network
        ports:
            - 1433:1433
        volumes:
            - mssql:/var/opt/mssql
    # dotnetarchitecture_mongo:
    #     image: mongo
    #     container_name: dotnetarchitecture_mongo
    #     environment:
    #         MONGO_INITDB_DATABASE: db
    #         MONGO_INITDB_ROOT_PASSWORD: P4ss-W0rd
    #         MONGO_INITDB_ROOT_USERNAME: admin
    #     networks:
    #         - network
    #     ports:
    #         - 27017:27017
    #     volumes:
    #         - mongo:/data/db
    # dotnetarchitecture_redis:
    #     image: redis
    #     container_name: dotnetarchitecture_redis
    #     command: redis-server --requirepass P4ss-W0rd
    #     networks:
    #         - network
    #     ports:
    #         - 6379:6379
    #     volumes:
    #         - redis:/data

networks:
    network:

volumes:
    mssql:
    # mongo:
    # redis:
